### ISSUE TITLE
Little Snitch Subscription Error

### ISSUE THREAD

**Issue by grandviewsound** [fabston/little-snitch-blocklist#1]
## Describe the bug

When attempting to subscribe to the blocklist in Little Snitch v4 and v5, it prompts with an error, saying "An error occurred while loading the rule group.  Too many rules, hostnames, or domains in rule group (more than 200,000)."

### Steps to reproduce
Subscribe to https://blocklist.fabston.dev/rules

### Expected behavior
Expected the blocklist to be created without an error.

### Environment
 - OS: macOS 11.6.1 & macOS 10.15

### Additional context

![Screen Shot 2021-11-28 at 11 28 21 AM](https://user-images.githubusercontent.com/32183888/143777163-39e095f2-9e5c-44a3-ab4d-3608a94070c5.png)
.

**Comment by fabston** [comment]
Ugh, I'd have to remove a few filters from the list so it works again. Sadly Little Snitch caps it to max 200,000 entries.

**Comment by fabston** [comment]
In the next update this issue will be resovled @grandviewsound.

**Comment by grandviewsound** [comment]
Thanks.  Sorry to cause you any inconvenience

**Comment by fabston** [comment]
No problem at all. You can actually just update your blocklist or re-add it and it should work just fine.

**Comment by grandviewsound** [comment]
That worked.  Thanks for make the list.
