### ISSUE TITLE
Opportunity to shirk size of blocklist significantly

### ISSUE THREAD

**Issue by ph00lt0** [fabston/little-snitch-blocklist#10]
As of Little Snitch 4.2, blocklists can be a lot more compact 

I have done this for my own blocklist which just got Little Snitch support: 
https://github.com/ph00lt0/blocklist/blob/master/little-snitch-blocklist.lsrules

See docs: https://help.obdev.at/littlesnitch4/ref-lsrules-file-format

**Comment by fabston** [comment]
Hi there, thanks for reaching out. I will update to the new format soon.
