### ISSUE TITLE
Blocklist exceeds 200,000 entry maximum for Little Snitch 5.5

### ISSUE THREAD

**Issue by brunston** [fabston/little-snitch-blocklist#14]
I am running a registered copy of Little Snitch 5.5 and encountered "An error occurred while loading the rule group" when trying to install this blocklist.

```
Too many rules, hostnames or domains in rule group (exceeded the allowed maximum of 200,000 entries).
```

I believe this happened in [this commit](https://github.com/fabston/little-snitch-blocklist/commit/484868a40496da64057e43a276414f851b43cb8a)

**Comment by fabston** [comment]
Hi there,

I will trim down the list today so it’ll be below 200k entries. Sorry about that.

**Comment by brunston** [comment]
Thanks!

**Comment by fabston** [comment]
@brunston has been fixed now.
