### ISSUE TITLE
Blocklist exceeds 200,000 entry maximum for Little Snitch 5..6

### ISSUE THREAD

**Issue by takovermeulen** [fabston/little-snitch-blocklist#19]
Little Snitch 5.6 enforces a 200k entry limit per rule groups, and as of today the list is 202k+ entries, which causes Little Snitch refusing to load the most recent rule group.

Can we prune the blocklist and/or split it up in two?

**Comment by rmontanana** [comment]
Same for me!

**Comment by fabston** [comment]
Will fix that right now, sorry about that... sometimes we just hit that limit

**Comment by fabston** [comment]
Alright, trimmed the list down to 109k. If I add other lists back, it will result in the list being above 200k again.
