### ISSUE TITLE
Looks like the site is down

### ISSUE THREAD

**Issue by ridinghoodmedia** [fabston/little-snitch-blocklist#2]
https://blocklist.fabston.dev/ doesn't work

**Comment by graafsjur** [comment]
https://blocklist.fabston.dev/ still worked a couple of weeks ago, now it doesn't?

**Comment by fabston** [comment]
I will have to move the blocklist to a new domain. Until then you can use: https://raw.githubusercontent.com/fabston/little-snitch-blocklist/main/blocklist.txt

**Comment by ridinghoodmedia** [comment]
Thanks @fabston

**Comment by fabston** [comment]
Closing this issue now. Please use the github raw url. Also fixed daily updates.
