### ISSUE TITLE
Rule for dpm.demdex.net conflicts with System Rule for allowing all connection to mDNS Responder.

### ISSUE THREAD

**Issue by NormG1** [fabston/little-snitch-blocklist#3]
### Which domain should be removed?

The rules in your ruleset contradict each other about whether connections to these hostnames should be allowed or not. One rule in the Fabston Blocklisdt denies connections to domain dpm.demdex.net while another rule mDNS Responder allows any connection.

### Why should the domain be removed?

mDNS Responder is a LOCKED SYSTEM RULE in Little Snitch that allows all connections. It cannot be edited to add an exception for dpm.demdex.net at 162.252.172.57.

I have no real idea what any of this stuff does, as I am not a programmer or engineer. So I have a very vague idea that mDNS Responder must be allowed to connect.

![@2x Xnip Wednesday May  112022 02-31 PM](https://user-images.githubusercontent.com/19417613/167931285-61ab765c-5e0e-4fc4-86d3-e9dceaab302e.jpg)

**Comment by fabston** [comment]
Hello, thanks for reaching out. I’ll look into and add an exclusion for that domain.

**Comment by fabston** [comment]
I have added `dpm.demdex.net` to the false-positive list as you can see [here](https://github.com/fabston/little-snitch-blocklist/commit/89ba9804a970806766c0320aff0b7d15fbee503e).

**Comment by NormG1** [comment]
It did, working great now. That was a weird thing. Any idea what it was or what it is doing?

From: Fabston ***@***.***>
Reply-To: fabston/little-snitch-blocklist ***@***.***>
Date: Wednesday, May 18, 2022 at 10:13 PM
To: fabston/little-snitch-blocklist ***@***.***>
Cc: Norm Gilbert ***@***.***>, Mention ***@***.***>
Subject: Re: [fabston/little-snitch-blocklist] Rule for dpm.demdex.net conflicts with System Rule for allowing all connection to mDNS Responder. (Issue #3)


@NormG1<https://github.com/NormG1> I was just wondering if the commit fixed it for you?

**Comment by fabston** [comment]
I am personally not sure why I had to whitelist that domain. But glad to hear it’s working now.
