### ISSUE TITLE
There is a domain on Reddit that should not be blocked. See screensht.

### ISSUE THREAD

**Issue by NormG1** [fabston/little-snitch-blocklist#4]
### Which domain should be removed?
click.redditmail.co
![@2x Xnip Tuesday May  242022 00-16 AM](https://user-images.githubusercontent.com/19417613/170379666-848d4052-dd13-4da9-838b-a4c84a279827.jpg)
![@2x Xnip Wednesday May  252022 05-21 PM](https://user-images.githubusercontent.com/19417613/170379726-052813d4-0561-40d0-b3a1-b72f33ca3667.jpg)
m
### Why should the domain be removed?
I receive article summaries in an e-mail from Reddit from groups and topics I follow. 

Clicking on the link in the e-mail to go to the article fails because of this rule. See the screenshots. Discovered this by testing with both Edge and Safari on Mac and then the same link on my iPhone. The link connects on iOS, but fails on Mac OS. Please take a look at some of the other Reddit links as some may be benign.

**Comment by fabston** [comment]
Hi there,

I have added `click.redditmail.co` to the [false-positive](https://github.com/fabston/little-snitch-blocklist/commit/680d4b97b802530dad0c2f02314961add05c8f45) list.
