### ISSUE TITLE
Ruleset Subscription Failure

### ISSUE THREAD

**Issue by blackice19** [fabston/little-snitch-blocklist#5]
Hi,

The subscription to the ruleset found at https://raw.githubusercontent.com/fabston/little-snitch-blocklist/main/blocklist.txt is failing.

The reason is there are 200,001 rules instead of 200,000 (please see attached screenshot). Updates attempts to existing subscription also have failed.

Could this be looked into please.

Thanks

<img width="259" alt="Screenshot 2022-06-13 at 1 53 48 pm" src="https://user-images.githubusercontent.com/84452822/173358444-fa8bd06c-07ac-442c-85eb-20c07d79582c.png">

**Comment by fabston** [comment]
Sigh. Will look into that in a bit.

**Comment by NormG1** [comment]
![@2x Xnip Tuesday June  142022 01-41 PM](https://user-images.githubusercontent.com/19417613/173665404-db87221c-343d-4e50-aece-8eacfa440649.jpg)


Here's the Mac view of the error . . .

Looks like either Objective Development needs to up the maximum number of rules, or you need to get rid of one rule out of 200,001 or you need to go to two rules lists to avoid the 200,000 rue limit.

**Comment by blackice19** [comment]
Hi, Thank you so much for fixing this & apologies for the late replies.

I have been looking at these filter block lists and wanted to share my experience. Nominally, Steve Black's & Anudeep's lists cover the major items. Something like PGL yoyo is pulled in by Steve Black's list frequently, so can be got rid of. Similarly for Adaway, Adguard lists, there is a huge overlap. Lightswitchdan's list is quite aggressive, I found. 

This is always a case of a dog trying to catch its tail. No list is perfect for everyone! 
OD had once told me that their tool is not planned to similar to DNS filtering, like  DNSCrypt. So we would probably be limited by rules in that scenario.

Thanks

**Comment by fabston** [comment]
No worries and youre welcome.

I have moved your input [here](https://github.com/fabston/little-snitch-blocklist/discussions/7). Lets go over it there.

**Comment by NormG1** [comment]
I doubt they will do anything unless you ask them to and give them a reason.

Regards,


Norm Gilbert
World Traveler & Photographer
Retired & Enjoying Life, Ltd.
***@***.***
 +1 (415) 465-4220
 +1 (415) 423-3355
 www.instagram.com/fogcitynative/
 340 S. Lemon Ave. STE 6148, Walnut, CA 91789
 Calle 45d #77a-11 Medellin 050031 Colombia
     

Someone's Watching You . . .One of my favorite photos from Lisbon. Click here to see them all.


On Jun 14, 2022, at 8:43 PM, fabston ***@***.***> wrote:

﻿
Hi,

I have just fixed this by removing one blocklist from the list. I hope Little Snitch is going to increase the limit in the future.

Sorry about that.
