### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by Taddaeus** [fabston/little-snitch-blocklist#6]
I just faced with the Little Snitch 200.000-rule-limitation when I wanted to (re-)subscribe to my favorite and essential little-snitch-blocklist. Since the list keeps growing and has now apparently exceeded the 200.000-limitation, the subscription is unfortunately no longer possible. Is there a workaround, or could you split the list? **Please**, please keep the awsome Fabston`s list for Little-Snitch-users alive!

**Comment by fabston** [comment]
Hi, 

I have just fixed this by removing one blocklist from the list. I hope Little Snitch is going to increase the limit in the future. 

Sorry about that.

**Comment by Taddaeus** [comment]
Hi

Thanks! I will make a request at Objective Development.
Maybe you too.

Kind regards
Gunnar

**Comment by fabston** [comment]
Yea I’ve done that already but it seems like they won’t be adding it soon… But definitely a good idea to let them know.
