### ISSUE TITLE
Blocking good awstrack.me, used for filing Class Action Claims in Facebook Lawsuit.

### ISSUE THREAD

**Issue by NormG1** [fabston/little-snitch-blocklist#9]
### Discussed in https://github.com/fabston/little-snitch-blocklist/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **NormG1** June 26, 2022</sup>
ERROR MESSAGE: Hmmm… can't reach this page. It looks like the webpage at http://lzzgcc5d.r.us-east-1.awstrack.me/L0/http:%2F%2Fwww.FBInternetTrackingSettlement.com/1/010001819c277954-9836f484-8da7-4ca3-a0fa-6226d78f22c1-000000/eNJ2dG_RXjGABcf_OLmkC_l1iRo=275 might be having issues, or it may have moved permanently to a new web address.

Cannot block awstrack.me at the domain level, only for malicious sites individually hosted there.

![@2x Xnip Sunday June  262022 01-46 PM](https://user-images.githubusercontent.com/19417613/175829553-4529e2ed-63d9-49c3-9c95-b16b3a9a227d.jpg)
![@2x Xnip Sunday June  262022 01-49 PM](https://user-images.githubusercontent.com/19417613/175829555-7ef85270-10f7-49d1-a42a-733684f9a978.jpg)
![@2x Xnip Sunday June  262022 01-51 PM](https://user-images.githubusercontent.com/19417613/175829603-9ed8b0d3-ffe9-48af-9743-c9cea7ccc3e1.jpg)

</div>

**Comment by fabston** [comment]
Hi, I have [added](https://github.com/fabston/little-snitch-blocklist/commit/0bdd00fddd0c8d237f16fb30f103069709d9c1ca) "awstrack.me" to the false positive list. Will be updated at 3 PM UTC. Cheers!
